//! Raw bindings to sherpa-onnx's offline speaker diarization C API
//! (`sherpa-onnx/c-api/c-api.h`), generated by bindgen at build time from
//! the pinned release (sherpa-onnx 1.13.7; the archives and their checksums
//! are in `build.rs`). The library is linked dynamically and ONNX Runtime
//! comes with it, so the core libraries and any CUDA providers travel beside the binary
//! that links this crate (`dettivo-engine-diarize`), which sets its run
//! path from `DEP_SHERPA_ONNX_LIB_DIR`. Every function is `unsafe` and
//! follows the C API's ownership rules: a result is destroyed with
//! `SherpaOnnxOfflineSpeakerDiarizationDestroyResult`, a segment array
//! with `...DestroySegment`, the diarizer with
//! `SherpaOnnxDestroyOfflineSpeakerDiarization`. The engine crate holds
//! the safe wrapper.
//! CPU and CUDA build the same calibrated clustering in `source_build.rs`.
//! CUDA also applies the checked convolution-search patch.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    missing_docs,
    unsafe_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// The sherpa-onnx release these bindings were built from.
pub const SOURCE_VERSION: &str = "1.13.7";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_api_keeps_explicit_zero_threshold_and_durations() {
        if std::env::var_os("DETTIVO_TEST_CAPI_ZERO").is_none() {
            let output = std::process::Command::new(std::env::current_exe().unwrap())
                .args([
                    "--exact",
                    "tests::c_api_keeps_explicit_zero_threshold_and_durations",
                ])
                .env("DETTIVO_TEST_CAPI_ZERO", "1")
                .output()
                .unwrap();
            assert!(output.status.success());
            let log = String::from_utf8_lossy(&output.stderr);
            assert!(log.contains("threshold=0)"), "{log}");
            assert!(
                log.contains("min_duration_on=0, min_duration_off=0)"),
                "{log}"
            );
            return;
        }
        // SAFETY: this C configuration contains integers, floats and nullable pointers.
        let mut config: SherpaOnnxOfflineSpeakerDiarizationConfig = unsafe { std::mem::zeroed() };
        config.segmentation.debug = 1;
        config.clustering.num_clusters = -1;
        // SAFETY: null model paths are supported and return a null diarizer.
        let result = unsafe { SherpaOnnxCreateOfflineSpeakerDiarization(&config) };
        assert!(result.is_null());
    }

    #[test]
    fn the_library_reports_the_pinned_version() {
        // SAFETY: the call takes no arguments and returns a static string.
        let version = unsafe { std::ffi::CStr::from_ptr(SherpaOnnxGetVersionStr()) };
        assert_eq!(version.to_str().unwrap(), SOURCE_VERSION);
    }

    #[test]
    fn a_missing_model_yields_a_null_diarizer() {
        let missing = std::ffi::CString::new("/nonexistent/model.onnx").unwrap();
        let provider = std::ffi::CString::new("cpu").unwrap();
        let config = SherpaOnnxOfflineSpeakerDiarizationConfig {
            segmentation: SherpaOnnxOfflineSpeakerSegmentationModelConfig {
                pyannote: SherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig {
                    model: missing.as_ptr(),
                    window_shift_ratio: 0.1,
                },
                num_threads: 1,
                debug: 0,
                provider: provider.as_ptr(),
            },
            embedding: SherpaOnnxSpeakerEmbeddingExtractorConfig {
                model: missing.as_ptr(),
                num_threads: 1,
                debug: 0,
                provider: provider.as_ptr(),
            },
            clustering: SherpaOnnxFastClusteringConfig {
                num_clusters: -1,
                threshold: 0.5,
            },
            min_duration_on: 0.3,
            min_duration_off: 0.5,
        };
        // SAFETY: every pointer in the config is valid for the call; NULL
        // is the documented answer for a model that does not load.
        let sd = unsafe { SherpaOnnxCreateOfflineSpeakerDiarization(&config) };
        assert!(sd.is_null());
    }
}
