//! What never reaches the text: the known filler hallucinations Whisper
//! writes into silence (the macOS `MeetingTranscriptHallucinationFilter`
//! lists, canonicalised the same way, plus the bracketed markers
//! whisper.cpp prints for a window without speech) and the near-silence
//! guard that keeps a chunk under the macOS speech activation floor away
//! from the engine altogether.

/// The macOS `speechActivationFloor`: RMS (0 to 1) of a frame that counts
/// as speech; a chunk under it is silence.
pub const SILENCE_RMS_FLOOR: f64 = 0.0065;

/// The frame the floor is judged over, in samples at 16 kHz (200 ms): a
/// word is longer than one frame and a five-minute chunk is a great many,
/// so one utterance in a long silence is speech and never averages away.
pub const SILENCE_FRAME: usize = 3_200;

/// Phrases dropped wherever they appear, whatever their length.
pub const KNOWN_HALLUCINATIONS: &[&str] = &[
    "продолжение следует",
    "to be continued",
    "ご視聴ありがとうございました",
    "ご清聴ありがとうございました",
    "thanks for watching",
    "thank you for watching",
    "subtitle generated by amara org",
    "subtitles by amara org",
    // whisper.cpp's own markers for a window it heard nothing in.
    "[blank_audio]",
    "[inaudible]",
    "[silence]",
    "[music]",
];

/// Phrases dropped only from a system-audio segment of eight seconds or
/// more, where a whole stretch of music or silence became one filler.
pub const LONG_GENERIC_SYSTEM_PHRASES: &[&str] = &[
    "thank you",
    "thanks",
    "mm hmm",
    "mhm",
    "hmm",
    "okay",
    "thats okay",
    "ok",
    "yeah",
    "ja",
    "absolut",
    "absolutely",
    "oh",
];

/// The length from which a generic phrase on system audio is a filler.
pub const LONG_GENERIC_MS: u64 = 8_000;

/// The macOS canonical form: lower case, sentence punctuation and
/// apostrophes removed, hyphens as spaces, whitespace collapsed.
pub fn canonical(text: &str) -> String {
    text.to_lowercase()
        .chars()
        .filter_map(|c| match c {
            '…' | '.' | '!' | '?' | ',' | ':' | ';' | '\'' | '’' => None,
            '-' => Some(' '),
            other => Some(other),
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

/// True when a segment's text is a known filler: empty, one of the
/// exact phrases, or a generic phrase on eight seconds or more of system
/// audio.
pub fn should_drop(text: &str, duration_ms: u64, from_system: bool) -> bool {
    let c = canonical(text);
    if c.is_empty() || KNOWN_HALLUCINATIONS.contains(&c.as_str()) {
        return true;
    }
    from_system
        && duration_ms >= LONG_GENERIC_MS
        && LONG_GENERIC_SYSTEM_PHRASES.contains(&c.as_str())
}

/// Root mean square of 16-bit samples, 0 to 1.
pub fn rms(samples: &[i16]) -> f64 {
    if samples.is_empty() {
        return 0.0;
    }
    let sum: f64 = samples
        .iter()
        .map(|s| {
            let v = f64::from(*s) / 32_768.0;
            v * v
        })
        .sum();
    (sum / samples.len() as f64).sqrt()
}

/// True when every `SILENCE_FRAME` of the chunk stays under `floor` and
/// the chunk must not reach the engine. The floor is a speech activation
/// level, so it is judged per frame: a one-second utterance in a
/// five-minute chunk averages to well under the floor over the whole
/// chunk and is still speech.
pub fn is_near_silent(samples: &[i16], floor: f64) -> bool {
    samples
        .chunks(SILENCE_FRAME)
        .all(|frame| rms(frame) < floor)
}

/// Speech-bearing input with conservative silence trimmed from its edges.
/// Activation uses the configured floor; trimming uses one tenth of that floor
/// and 400 ms of padding, preserving quiet word onsets and tails around speech.
/// The returned indices stay relative to the original chunk for timestamp repair.
pub fn speech_bounds(samples: &[i16], floor: f64) -> Option<std::ops::Range<usize>> {
    if samples.is_empty() {
        return None;
    }
    if floor <= 0.0 {
        return Some(0..samples.len());
    }
    let mut active = false;
    let mut first = None;
    let mut last = 0;
    for (index, frame) in samples.chunks(SILENCE_FRAME).enumerate() {
        let level = rms(frame);
        active |= level >= floor;
        if level >= floor / 10.0 {
            first.get_or_insert(index * SILENCE_FRAME);
            last = (index * SILENCE_FRAME + frame.len()).min(samples.len());
        }
    }
    if !active {
        return None;
    }
    let padding = 2 * SILENCE_FRAME;
    Some(first?.saturating_sub(padding)..(last + padding).min(samples.len()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_second_of_speech_in_five_minutes_of_silence_is_not_silent() {
        let mut pcm = vec![0i16; 300 * 16_000];
        // One second at RMS 0.1, then 299 s of nothing: the whole-chunk
        // RMS is about 0.0058, under the floor.
        for s in &mut pcm[16_000..32_000] {
            *s = 3_277;
        }
        assert!(rms(&pcm) < SILENCE_RMS_FLOOR, "{}", rms(&pcm));
        assert!(!is_near_silent(&pcm, SILENCE_RMS_FLOOR));
        assert!(is_near_silent(&vec![0i16; 300 * 16_000], SILENCE_RMS_FLOOR));
        assert!(is_near_silent(&[], SILENCE_RMS_FLOOR));
        // Noise just under the floor in every frame is still silence.
        let quiet: Vec<i16> = (0..48_000)
            .map(|i| if i % 2 == 0 { 150 } else { -150 })
            .collect();
        assert!(is_near_silent(&quiet, SILENCE_RMS_FLOOR));
    }

    #[test]
    fn canonical_form_matches_the_macos_rules() {
        assert_eq!(canonical("Thanks for watching!"), "thanks for watching");
        assert_eq!(canonical("  Mm-hmm... "), "mm hmm");
        assert_eq!(canonical("That's okay."), "thats okay");
    }

    #[test]
    fn the_known_hallucinations_and_the_blank_markers_are_dropped() {
        assert!(should_drop("Thanks for watching!", 900, false));
        assert!(should_drop(" [BLANK_AUDIO] ", 10_000, false));
        assert!(should_drop("[inaudible]", 500, true));
        assert!(should_drop("", 500, true));
        assert!(!should_drop("ask what you can do", 900, false));
        // A generic phrase is a filler only on a long stretch of system audio.
        assert!(should_drop("Thank you.", LONG_GENERIC_MS, true));
        assert!(!should_drop("Thank you.", LONG_GENERIC_MS, false));
        assert!(!should_drop("Thank you.", 900, true));
    }
}
