//! Raw bindings to NeMo-Speech.cpp's standalone diarization C API
//! (`nemo_speech/diar.h`, with the status codes and last-error accessor it
//! shares with `asr.h`), generated by bindgen at build time from the pinned
//! source (the commits and checksums are in `build.rs`). The libraries are
//! linked dynamically and carry their own ggml, so they travel beside the
//! binary that links this crate (`dettivo-engine-nemotron`), which sets its
//! run path from `DEP_NEMO_SPEECH_LIB_DIR`. Every function is `unsafe` and
//! follows the C ABI's rules: opaque handles, size-prefixed config structs,
//! a status code per call with the reason in `nemo_speech_asr_last_error`,
//! and no exceptions across the boundary. The engine crate holds the safe
//! wrapper.
//!
//! Built with the `vulkan` or `cuda` feature the library carries that ggml
//! backend; a model created with `gpu = 0` takes the first GPU the ggml
//! registry reports, `gpu = -1` stays on the CPU. That registry is bound
//! too (`ggml_backend_dev_*`), from the ggml copy inside
//! `libnemo_speech_asr.so`, so the engine can name the device.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    missing_docs,
    unsafe_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// The NeMo-Speech.cpp commit these bindings were built from.
pub const SOURCE_COMMIT: &str = env!("NEMO_SPEECH_CPP_COMMIT");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_library_reports_its_version_and_refuses_a_missing_model() {
        let path = std::ffi::CString::new("/nonexistent/model.gguf").unwrap();
        let config = nemo_speech_diar_model_config {
            size: std::mem::size_of::<nemo_speech_diar_model_config>(),
            model_path: path.as_ptr(),
            gpu: -1,
            preset: std::ptr::null(),
            chunk_frames: 0,
            right_context_frames: 0,
            left_context_frames: -1,
            fifo_frames: 0,
            spkcache_frames: 0,
            update_period_frames: 0,
        };
        let mut model = std::ptr::null_mut();
        // SAFETY: the config points at a live NUL-terminated path, `model`
        // is a valid out pointer, and the version and error strings are
        // static or thread-local C strings owned by the library.
        let (version, status, error) = unsafe {
            let version = std::ffi::CStr::from_ptr(nemo_speech_asr_version());
            let status = nemo_speech_diar_create(&config, &mut model);
            let error = std::ffi::CStr::from_ptr(nemo_speech_asr_last_error());
            (
                version.to_string_lossy().into_owned(),
                status,
                error.to_string_lossy().into_owned(),
            )
        };
        assert_eq!(version, "nemo-speech-asr 0.1.0");
        assert_ne!(status, nemo_speech_asr_status_NEMO_SPEECH_ASR_OK);
        assert!(model.is_null());
        assert!(error.contains("model.gguf"), "{error}");
        assert_eq!(SOURCE_COMMIT.len(), 40);
        // SAFETY: the registry count takes no arguments; the CPU is always there.
        assert!(unsafe { ggml_backend_dev_count() } >= 1);
    }
}
