pragma Singleton
import QtQuick

QtObject {
    readonly property var languageCodes: ["auto", "af", "sq", "am", "ar", "hy", "as", "az", "ba", "eu", "be", "bn", "bs", "br", "bg", "yue", "ca", "zh", "hr", "cs", "da", "nl", "en", "et", "fo", "fi", "fr", "gl", "ka", "de", "el", "gu", "ht", "ha", "haw", "he", "hi", "hu", "is", "id", "it", "ja", "jw", "kn", "kk", "km", "ko", "lo", "la", "lv", "ln", "lt", "lb", "mk", "mg", "ms", "ml", "mt", "mi", "mr", "mn", "my", "ne", "no", "nn", "oc", "ps", "fa", "pl", "pt", "pa", "ro", "ru", "sa", "sr", "sn", "sd", "si", "sk", "sl", "so", "es", "su", "sw", "sv", "tl", "tg", "ta", "tt", "te", "th", "bo", "tr", "tk", "uk", "ur", "uz", "vi", "cy", "yi", "yo"]
    readonly property var languageLabels: [qsTr("Detect automatically"), qsTr("Afrikaans"), qsTr("Albanian"), qsTr("Amharic"), qsTr("Arabic"), qsTr("Armenian"), qsTr("Assamese"), qsTr("Azerbaijani"), qsTr("Bashkir"), qsTr("Basque"), qsTr("Belarusian"), qsTr("Bengali"), qsTr("Bosnian"), qsTr("Breton"), qsTr("Bulgarian"), qsTr("Cantonese"), qsTr("Catalan"), qsTr("Chinese"), qsTr("Croatian"), qsTr("Czech"), qsTr("Danish"), qsTr("Dutch"), qsTr("English"), qsTr("Estonian"), qsTr("Faroese"), qsTr("Finnish"), qsTr("French"), qsTr("Galician"), qsTr("Georgian"), qsTr("German"), qsTr("Greek"), qsTr("Gujarati"), qsTr("Haitian Creole"), qsTr("Hausa"), qsTr("Hawaiian"), qsTr("Hebrew"), qsTr("Hindi"), qsTr("Hungarian"), qsTr("Icelandic"), qsTr("Indonesian"), qsTr("Italian"), qsTr("Japanese"), qsTr("Javanese"), qsTr("Kannada"), qsTr("Kazakh"), qsTr("Khmer"), qsTr("Korean"), qsTr("Lao"), qsTr("Latin"), qsTr("Latvian"), qsTr("Lingala"), qsTr("Lithuanian"), qsTr("Luxembourgish"), qsTr("Macedonian"), qsTr("Malagasy"), qsTr("Malay"), qsTr("Malayalam"), qsTr("Maltese"), qsTr("Maori"), qsTr("Marathi"), qsTr("Mongolian"), qsTr("Myanmar"), qsTr("Nepali"), qsTr("Norwegian"), qsTr("Nynorsk"), qsTr("Occitan"), qsTr("Pashto"), qsTr("Persian"), qsTr("Polish"), qsTr("Portuguese"), qsTr("Punjabi"), qsTr("Romanian"), qsTr("Russian"), qsTr("Sanskrit"), qsTr("Serbian"), qsTr("Shona"), qsTr("Sindhi"), qsTr("Sinhala"), qsTr("Slovak"), qsTr("Slovenian"), qsTr("Somali"), qsTr("Spanish"), qsTr("Sundanese"), qsTr("Swahili"), qsTr("Swedish"), qsTr("Tagalog"), qsTr("Tajik"), qsTr("Tamil"), qsTr("Tatar"), qsTr("Telugu"), qsTr("Thai"), qsTr("Tibetan"), qsTr("Turkish"), qsTr("Turkmen"), qsTr("Ukrainian"), qsTr("Urdu"), qsTr("Uzbek"), qsTr("Vietnamese"), qsTr("Welsh"), qsTr("Yiddish"), qsTr("Yoruba")]
    property bool advanced: false
    readonly property var everyday: ["audio.input_device", "dictation.language", "dictation.vocabulary", "dictation.mode", "dictation.spoken_punctuation", "dictation.protect_tokens", "polish.transforms", "polish.default_preset", "polish.default_style", "speech.model", "speech.meeting_model", "llm.model", "llm.analysis_model", "osd.enabled", "osd.position", "osd.show_level", "osd.motion", "omarchy.osd", "hotkeys.pause_media", "hotkeys.sounds", "insert.backend", "insert.restore_clipboard", "history.keep_audio", "history.audio_retention_days", "meetings.keep_audio", "meetings.live", "meetings.analysis.auto", "meetings.diarization.enabled", "meetings.diarization.auto"]
    function show(key) {
        return advanced || everyday.indexOf(key) >= 0;
    }
}
