//! Raw bindings to parakeet.cpp's flat C API (`parakeet_capi.h`) and this
//! crate's shim over its process-global ggml backend, generated by bindgen
//! at build time from the pinned source (parakeet.cpp 0.5.0, ggml 0.13.0;
//! the commits and checksums are in `build.rs`). Every function is
//! `unsafe` and follows the C API's ownership rules: strings come back
//! `malloc`'d and go back through `parakeet_capi_free_string`, the last
//! error pointer belongs to the context. `dettivo-engine-parakeet` holds
//! the safe wrapper.
//!
//! Built with the `vulkan` feature the library carries ggml's Vulkan
//! backend and picks the first GPU the ggml registry reports unless
//! `PARAKEET_DEVICE=cpu` is set before the first inference.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    missing_docs,
    unsafe_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// The parakeet.cpp release these bindings were built from.
pub const SOURCE_VERSION: &str = "0.5.0";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_abi_and_source_version_are_the_pinned_ones() {
        // SAFETY: both calls take no pointers and return plain values.
        let (abi, version) = unsafe {
            let v = std::ffi::CStr::from_ptr(parakeet_sys_source_version());
            (parakeet_capi_abi_version(), v.to_str().unwrap().to_string())
        };
        assert_eq!(abi, 6, "parakeet_capi.h ABI moved; re-check the wrapper");
        assert_eq!(version, SOURCE_VERSION);
    }

    #[test]
    fn a_missing_model_yields_a_null_context() {
        let path = std::ffi::CString::new("/nonexistent/model.gguf").unwrap();
        // SAFETY: a valid NUL-terminated path; NULL is a documented result
        // and free is safe on NULL.
        unsafe {
            let ctx = parakeet_capi_load(path.as_ptr());
            assert!(ctx.is_null());
            parakeet_capi_free(ctx);
        }
    }
}
