-- Dettivo dictation bindings. Generated by `dettivo setup hyprland`; change the
-- keys in ~/.config/dettivo/config.toml ([hotkeys]) and run it again.
-- Load it from hyprland.lua after Omarchy's defaults: dofile(os.getenv("HOME") .. "/.config/hypr/dettivo.lua")
-- Omarchy binds the same keys to Voxtype; unbind takes them over.
hl.unbind("SUPER + ALT + SPACE")
hl.unbind("SUPER + ALT + D")
-- Hold to talk: press starts, release stops.
hl.bind("SUPER + ALT + SPACE", hl.dsp.exec_cmd("dettivo --quiet dictation start"), { description = "Dettivo: hold to talk" })
hl.bind("SUPER + ALT + SPACE", hl.dsp.exec_cmd("dettivo --quiet dictation stop"), { description = "Dettivo: hold to talk (release)", release = true })
-- Toggle: one press starts, the next stops.
hl.bind("SUPER + ALT + D", hl.dsp.exec_cmd("dettivo --quiet dictation toggle"), { description = "Dettivo: toggle dictation" })
hl.bind("SUPER + ALT + ESCAPE", hl.dsp.exec_cmd("dettivo --quiet dictation cancel"), { description = "Dettivo: cancel dictation" })
hl.bind("SUPER + ALT + SHIFT + D", hl.dsp.exec_cmd("dettivo --quiet dictation reinsert-last"), { description = "Dettivo: insert the last transcript again" })
